version: '3.8'

services:
  nginx:
    image: nginx:1.25
    ports:
      - "4001:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./php:/var/www/html
    depends_on:
      - php
    networks: 
      - backend # łączy sie z php
      - frontend # bo publiczny

  php:
    image: php:8.2-fpm
    volumes:
      - ./php:/var/www/html
    networks:
      - backend

  mysql:
    image: mysql:8.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2
    ports:
      - "6001:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: testuser
      PMA_PASSWORD: testpass
    depends_on:
      - mysql
    networks:
      - backend #żeby łączyć się z mysql
      - frontend #żeby był widoczny w przeglądarce

volumes:
  db_data:

networks:
  backend:
  frontend:
