services:
  nginx:
    image: nginx:1.25
    ports:
      - "4001:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./php:/var/www/html
    depends_on:
      - php
    networks: 
      - backend # łączy sie z php
      - frontend # bo publiczny

  php:
    image: php:8.2-fpm
    volumes:
      - ./php:/var/www/html
    networks:
      - backend

  mysql:
    image: mysql:8.3
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend
    secrets:
      - db_root_password
      - db_password


  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2
    ports:
      - "6001:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: testuser
      PMA_PASSWORD_FILE: /run/secrets/db_password
    depends_on:
      - mysql
    networks:
      - backend #żeby łączyć się z mysql
      - frontend #żeby był widoczny w przeglądarce
    secrets:
      - db_password
      

volumes:
  db_data:

networks:
  backend:
  frontend:

secrets:
  db_root_password:
    file: ./secrets/db_root_password.txt
  db_password:
    file: ./secrets/db_password.txt